---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: snapcast

spec:
  interval: 1h
  install:
    createNamespace: false

  chart:
    spec:
      chart: snapcast-server
      sourceRef:
        kind: HelmRepository
        name: snapcast

  values: {}
