apiVersion: apps/v1
kind: Deployment
metadata:
  name: mumble-server
  namespace: mumble-server
  labels:
    app: mumble-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mumble-server
  template:
    metadata:
      labels:
        app: mumble-server
    spec:
      containers:
      - name: mumble-server
        image: docker.io/mumblevoip/mumble-server:latest
        resources:
          limits:
            cpu: 250m
            memory: 512Mi
          requests:
            cpu: 50m
            memory: 512Mi
        env:
        - name: MUMBLE_CONFIG_database
          value: /data/volume/mumble-server.sqlite
        ports:
        - containerPort: 64738
          name: mumble
        volumeMounts:
        - name: data
          mountPath: "/data/volume"
          readOnly: false
      securityContext:
        fsGroup: 1000
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: mumble-server-data
