apiVersion: v1
kind: Service
metadata:
  name: mumble-server
  namespace: mumble-server
  annotations:
    external-dns.alpha.kubernetes.io/hostname: mumble.chaosdorf.space.
spec:
  type: LoadBalancer
  selector:
    app: mumble-server
  ports:
  - name: mumble-tcp
    protocol: TCP
    port: 64738
    targetPort: mumble
  - name: mumble-udp
    protocol: UDP
    port: 64738
    targetPort: mumble
