apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mumble-server-data
  namespace: mumble-server
spec:
  storageClassName: ceph-block
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
