apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: inventory-data
  namespace: inventory
spec:
  storageClassName: ceph-block
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi