apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: restreamer-data
  namespace: restreamer
spec:
  storageClassName: ceph-block
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: restreamer-config
  namespace: restreamer
spec:
  storageClassName: ceph-block
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi