apiVersion: v1
kind: ConfigMap
metadata:
  name: stream-recorder-config
data:
  recorder.sh: |
    #!/bin/sh

    # create output folders (if they do not already exist)
    mkdir -p /out/recordings/tmp

    # wait for incoming stream to record
    ffmpeg -listen 1 -i rtmp://0.0.0.0:1935 -c copy -c:v copy -c:a copy /out/recordings/tmp/active-recording.mkv

    # rename file with timestamp
    mv /out/recordings/tmp/active-recording.mkv /out/recordings/`date +%Y_%m_%d_%H-%M-%S`.mkv

    # give everything a moment to synchronize
    sleep 10

    # print file list
    ls -la /out/recordings
