apiVersion: apps/v1
kind: Deployment
metadata:
  name: stream-recorder-deployment
  labels:
    app: stream-recorder
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stream-recorder
  template:
    metadata:
      labels:
        app: stream-recorder
    spec:
      containers:
      - name: ffmpeg
        image: lscr.io/linuxserver/ffmpeg:latest
        command:
        - '/bin/sh'
        - '/config/recorder.sh'
        volumeMounts:
        - name: config
          mountPath: "/config"
          readOnly: true
        - name: data
          mountPath: /out
      volumes:
      - name: config
        configMap:
          name: stream-recorder-config
      - name: data
        persistentVolumeClaim:
          claimName: stream-recorder-data
