apiVersion: v1
kind: PersistentVolume
metadata:
  name: stream-recorder-data
  labels:
    app: stream-recorder
    volume: data
spec:
  capacity:
    storage: 16Ti
  nfs:
    server: fileserver.chaosdorf.space
    path: /srv/storage/tmp
  accessModes:
  - ReadWriteOnce
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: stream-recorder-data
  labels:
    app: stream-recorder
    volume: data
spec:
  accessModes:
  - ReadWriteOnce
  selector:
    matchLabels:
      app: stream-recorder
      volume: data
  resources:
    requests:
      storage: 16Ti
  volumeName: stream-recorder-data
  storageClassName: ''
  volumeMode: Filesystem
